name: Cypress Component Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Cypress Component Tests
      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v5
        with:
          runTests: true
          record: false
          configFile: cypress.config.ts 
          testingType: component
